runtime: python311

env: standard

entrypoint: python main.py

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  APP_ENV: production
  DEBUG: 'false'
  GOOGLE_CLOUD_PROJECT: your-project-id

handlers:
  - url: /.*
    script: auto
    secure: always

resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

# Network settings
network:
  instance_tag: marketing-intake-api
  name: default

# Health checks
liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 300

# Security settings
vpc_access_connector:
  name: projects/your-project-id/regions/us-central1/connectors/connector-name

# Service account for the application
service_account: marketing-intake-api@your-project-id.iam.gserviceaccount.com
