steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-intake-api:${COMMIT_SHA}'
      - '-t'
      - 'gcr.io/$PROJECT_ID/marketing-intake-api:latest'
      - '.'
    dir: '.'

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/marketing-intake-api:${COMMIT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/marketing-intake-api:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'marketing-intake-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/marketing-intake-api:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'APP_ENV=production,DEBUG=false'

  # Step 4: Enable required Google Cloud services
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'services'
      - 'enable'
      - 'run.googleapis.com'
      - 'containerregistry.googleapis.com'
      - 'firestore.googleapis.com'
      - 'vertexai.googleapis.com'
      - 'secretmanager.googleapis.com'

# Default substitution values
substitutions:
  _REGION: us-central1

# Options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Timeout for the entire build process
timeout: '1200s'
